# Generated by Django 3.2.18 on 2023-09-25 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import urbanvitaliz.apps.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0090_topic_for_projects_and_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="content",
            field=models.TextField(blank=True, default="", verbose_name="Contenu"),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de souscription",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_subscriptions",
                        to="projects.project",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                (
                    "on_site",
                    urbanvitaliz.apps.projects.models.SubscriptionOnSiteManager(),
                ),
            ],
        ),
    ]
